services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - currency_network

  currencyrateservice:
    image: trieuhoangnguyen/currencyrateservice:latest
    container_name: currencyrateservice
    ports:
      - "8080:8080"
    environment:
      - CurrencyRateEndpoint=${CurrencyRateEndpoint}
      - ConnectionStrings__CurrencyRateConnection=${ConnectionStrings__CurrencyRateConnection}
    depends_on:
      - sqlserver
    networks:
      - currency_network

  redis:
    image: redis:latest
    container_name: my_redis
    ports:
      - "6379:6379"

  converterservice:
    image: trieuhoangnguyen/converterservice:latest
    container_name: converterservice
    ports:
      - "8081:8080"
    environment:
      - GrpcCurrencyRateService=http://currencyrateservice:8080
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
      - currencyrateservice
    networks:
      - currency_network

networks:
  currency_network:

volumes:
  sql_data: