services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - currency_network
    platform: linux/amd64

  currencyrateservice:
    image: trieuhoangnguyen/currencyrateservice:latest
    container_name: currencyrateservice
    ports:
      - "8080:8080"
    environment:
      - CurrencyRateEndpoint=${CurrencyRateEndpoint}
      - ConnectionStrings__CurrencyRateConnection=${ConnectionStrings__CurrencyRateConnection}
    depends_on:
      - sqlserver
    networks:
      - currency_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - currency_network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # Management plugin web interface
    environment:
      RABBITMQ_DEFAULT_USER: "${RabbitMQ__User}"
      RABBITMQ_DEFAULT_PASS: "${RabbitMQ__Password}"
    networks:
      - currency_network

networks:
  currency_network:

volumes:
  sql_data:
  rabbitmq_data: