services:
  sqlserver: # Container port: 1433
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - currency_network
    platform: linux/amd64

  currencyrateservice: # Container port: 8080
    image: trieuhoangnguyen/currencyrateservice:latest
    container_name: currencyrateservice
    environment:
      - CurrencyRateEndpoint=${CurrencyRateEndpoint}
      - ConnectionStrings__CurrencyRateConnection=${ConnectionStrings__CurrencyRateConnection}
    depends_on:
      - sqlserver
    networks:
      - currency_network
    platform: linux/amd64

  redis: # Container port: 6379
    image: redis:latest
    container_name: redis
    networks:
      - currency_network
    platform: linux/amd64

  converterservice: # Container port: 8080
    image: trieuhoangnguyen/converterservice:latest
    container_name: converterservice
    environment:
      - GrpcCurrencyRateService=http://currencyrateservice:8080
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
      - currencyrateservice
    networks:
      - currency_network
    platform: linux/amd64

  nginx: # Container port: 80
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - "80:80"
    depends_on:
      - currencyrateservice
      - converterservice
    networks:
      - currency_network
    platform: linux/amd64

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ server port
      - "15672:15672" # Management plugin web interface
    environment:
      RABBITMQ_DEFAULT_USER: "${RabbitMQ__User}"
      RABBITMQ_DEFAULT_PASS: "${RabbitMQ__Password}"
    networks:
      - currency_network
    platform: linux/amd64

networks:
  currency_network:

volumes:
  sql_data: