services:
  sqlserver: # Container port: 1433
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - currency_network

  currencyrateservice: # Container port: 8080
    image: trieuhoangnguyen/currencyrateservice:latest
    container_name: currencyrateservice
    environment:
      - CurrencyRateEndpoint=${CurrencyRateEndpoint}
      - ConnectionStrings__CurrencyRateConnection=${ConnectionStrings__CurrencyRateConnection}
    depends_on:
      - sqlserver
    networks:
      - currency_network

  redis: # Container port: 6379
    image: redis:latest
    container_name: my_redis

  converterservice: # Container port: 8080
    image: trieuhoangnguyen/converterservice:latest
    container_name: converterservice
    environment:
      - GrpcCurrencyRateService=http://currencyrateservice:8080
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
      - currencyrateservice
    networks:
      - currency_network

networks:
  currency_network:

volumes:
  sql_data: