services:
  sqlserver: # Container port: 1433
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - currency_network

  currencyrateservice: # Container port: 8080
    build:
      context: .
      dockerfile: CurrencyRateService/Dockerfile
      args:
        BASE_PATH: CurrencyRateService
    container_name: currencyrateservice
    environment:
      - CurrencyRateEndpoint=${CurrencyRateEndpoint}
      - ConnectionStrings__CurrencyRateConnection=${ConnectionStrings__CurrencyRateConnection}
    depends_on:
      - sqlserver
    networks:
      - currency_network

  currencyratetest:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["sh", "-c", "dotnet restore CurrencyRateService.Tests/CurrencyRateService.Tests.csproj && dotnet test CurrencyRateService.Tests/CurrencyRateService.Tests.csproj --logger:trx"]    
    depends_on:
      - currencyrateservice
    networks:
      - currency_network

  redis: # Container port: 6379
    image: redis:latest
    container_name: my_redis

  converterservice: # Container port: 8080
    build:
      context: .
      dockerfile: ConverterService/Dockerfile
      args:
        BASE_PATH: ConverterService
    container_name: ConverterService
    environment:
      - GrpcCurrencyRateService=http://currencyrateservice:8080
      - Redis__ConnectionString=redis:6379,abortConnect=false
    depends_on:
      - redis
      - currencyrateservice
    networks:
      - currency_network

networks:
  currency_network:

volumes:
  sql_data:
