services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - currency_network

  currencyrateservice:
    build:
      context: .
      dockerfile: CurrencyRateService/Dockerfile
      args:
        BASE_PATH: CurrencyRateService
    container_name: currencyrateservice
    ports:
      - "8080:8080"
    environment:
      - CurrencyRateEndpoint=${CurrencyRateEndpoint}
      - ConnectionStrings__CurrencyRateConnection=${ConnectionStrings__CurrencyRateConnection}
    depends_on:
      - sqlserver
    networks:
      - currency_network

  currencyratetest:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["sh", "-c", "dotnet restore CurrencyRateService.Tests/CurrencyRateService.Tests.csproj && dotnet test CurrencyRateService.Tests/CurrencyRateService.Tests.csproj --logger:trx"]    
    depends_on:
      - currencyrateservice
    networks:
      - currency_network

  converterservice:
    image: trieuhoangnguyen/converterservice:latest
    container_name: converterservice
    ports:
      - "8081:8080"
    environment:
      - GrpcCurrencyRateService=currencyrateservice
    depends_on:
      - currencyrateservice
    networks:
      - currency_network

networks:
  currency_network:

volumes:
  sql_data:
