name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set up Docker Compose
      run: |
        docker-compose --version

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and run tests using Docker Compose
      env:
        SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
        CurrencyRateEndpoint: ${{ secrets.CurrencyRateEndpoint }}
        ConnectionStrings__CurrencyRateConnection: ${{ secrets.CONNECTIONSTRINGS__CURRENCYRATECONNECTION }}
      run: |
        docker-compose -f docker-compose.ci-test.yaml up --build --abort-on-container-exit --exit-code-from currencyratetest

    - name: Upload CurrencyRateService test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: CurrencyRateService-TestResults
        path: CurrencyRateService.Tests/TestResults/*.trx
    
    - name: Build CurrencyRateService Docker image
      env:
        TAG: ${{ github.sha }}
      run: |
        docker buildx build --build-arg BASE_PATH=CurrencyRateService --file CurrencyRateService/Dockerfile --tag trieuhoangnguyen/currencyrateservice:$TAG --push .

    - name: Tag CurrencyRateService image as latest
      if: github.ref == 'refs/heads/main'
      env:
        TAG: ${{ github.sha }}
      run: |
        TAG=${{ github.sha }}
        docker pull trieuhoangnguyen/currencyrateservice:$TAG
        docker tag trieuhoangnguyen/currencyrateservice:$TAG trieuhoangnguyen/currencyrateservice:latest
        docker push trieuhoangnguyen/currencyrateservice:latest
