name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Set up Docker Compose
      run: |
        docker-compose --version

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        TAG=${{ github.sha }}
        docker buildx build --file CurrencyRateService/Dockerfile --tag trieuhoangnguyen/currencyrateservice:$TAG --push .

    - name: Tag image as latest
      if: github.ref == 'refs/heads/main'
      run: |
        docker pull trieuhoangnguyen/currencyrateservice:$TAG
        docker tag trieuhoangnguyen/currencyrateservice:$TAG trieuhoangnguyen/currencyrateservice:latest
        docker push trieuhoangnguyen/currencyrateservice:latest
